spring:
  datasource:
    url: jdbc:mysql://localhost:8080/filmplus
    username: ironhacker
    password: 1r0nh4ck3r
   ## driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
